Add gold per turn to overview
MattGibney/DarkThrone pull request #77
Opened 2024-12-05 06:43 UTC by Rihoj

Added a gold per turn display as requested in discord.

2024-12-14 23:45 UTC, MattGibney requested changes
UX wise, this change is fine. But the Implementation is not appropriate I am afraid. Rather than adding an additional API call for this data. Please update the Serialisation of the Authed Player object. It already includes all of the critical information required to render this page. Adding an additional API call for this is un-necessarily slow and wasteful.

If you have any questions about this. Please let me know.

2024-12-14 23:45 UTC, MattGibney commented on apps/api/src/controllers/player.ts
> +    }
I know that I am rejecting this approach and so this code will not make it in, however I must point out to you that this introduces a vulnerability. With the code as written, it would be possible to request the gold per turn for ANY player. This is sensitive information and should not be know to anyone but the player themselves.

When making changes like this, you MUST be careful to not open the API up to the possibility of abuse.

2024-12-15 07:34 UTC, Rihoj commented
The PR has been updated with your comments addressed. Thank you!

2024-12-15 14:46 UTC, MattGibney approved these changes
Looks good to me.

2024-12-15 14:48 UTC, merged